services:
  python:
    image: ex02/python:3.11
    build: ./python
    container_name: 'Home-Credit-Default-Risk'
    stdin_open: true
    tty: true
    working_dir: '/tmp/work'
    volumes:
      - ../python:/tmp/work
